// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK40uPXJru7FfzgGVFWGD7p9queADJg4M',
    appId: '1:289648665608:android:a673abe0be169fd0399dbd',
    messagingSenderId: '289648665608',
    projectId: 'ibrahim-flutter-steps-tracker',
    storageBucket: 'ibrahim-flutter-steps-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHxNsM6rWxabykWBOhEqJsoBj1fznckdw',
    appId: '1:289648665608:ios:883a72b3f482d56d399dbd',
    messagingSenderId: '289648665608',
    projectId: 'ibrahim-flutter-steps-tracker',
    storageBucket: 'ibrahim-flutter-steps-tracker.appspot.com',
    iosClientId: '289648665608-d8k6bre1gnhg9agn7iflrd779krko91e.apps.googleusercontent.com',
    iosBundleId: 'com.ibrahimshaglil.flutterStepsTracker',
  );
}
